### ISSUE TITLE
Possible bug in checksum calculation

### ISSUE THREAD

**Issue by carlkesselman** [ini-bdds/minid#10]
The function compute checksum has a hash constructor as a default argument.  However, this is only evaluated once, and the same checksum object will be reused in subsequent calls.  Since hash.update() is used, a second call to compute_checksum will use the previous state of the hash object and just add additional text to it.    Hence, if you rehash the second file  you won’t get the same checksum the second time.

**Comment by kylechard** [comment]
Fixed
