### ISSUE TITLE
Attempt to register a non-existent file fails in the wrong way

### ISSUE THREAD

**Issue by ianfoster** [ini-bdds/minid#25]
% **minid --test --register foo**
2018-03-07 15:30:23,922 - INFO - Checking if the entity foo already exists on the server: http://minid.bd2k.org/minid
Traceback (most recent call last):
 File “/Users/ian/miniconda/bin/minid”, line 11, in <module>
   sys.exit(main())
 File “/Users/ian/miniconda/lib/python2.7/site-packages/minid_client/minid.py”, line 130, in main
   _main()
 File “/Users/ian/miniconda/lib/python2.7/site-packages/minid_client/minid.py”, line 90, in _main
   checksum,
UnboundLocalError: local variable ‘checksum’ referenced before assignment

**Comment by mikedarcy** [comment]
Fixed in 15a2009.
