### ISSUE TITLE
current set of minid metadata fields and allowed values?

### ISSUE THREAD

**Issue by bheavner** [ini-bdds/minid#30]
Where is the best current place to get info about fields and expected values for minid metadata?

For example, it looks like the python client returns these fields/types:

identifier = "character",
creator = "character",
created = "character",
checksum = "character",
checksum_function = "character",
status = "character",
locations = "list",
titles = "list"

But in the JSON, I also see content_key, obsoleted_by, orcid, and short_identifier.

And I think the status field can have values like "ACTIVE" and "TOMBSTONED"... are there other values?

**Comment by kylechard** [comment]
We should do a better job documenting these fields. The best source of information at present is the REST API documentation: https://github.com/fair-research/minid-server/blob/master/rest-api.rst

**Comment by bheavner** [comment]
That'll do for now - thanks @kylechard .
