### ISSUE TITLE
hi! is this project active?

### ISSUE THREAD

**Issue by jhpoelen** [ini-bdds/minid#41]
Hi!

I am evaluating using minid and was wondering, is this project still active?

thx,
-jorrit

**Comment by mikedarcy** [comment]
Hi,

Yes the project is still active. We are working on the next version of both the client and server software. Sorry for the delayed response. More info to come shortly.  Thanks for your interest!

**Comment by NickolausDS** [comment]
Version 2.0.0 is out now and on PyPi
