### ISSUE TITLE
minid-config.cfg not created during the first login

### ISSUE THREAD

**Issue by proccaserra** [ini-bdds/minid#53]
minid-client 2.0.0b1

`minid login` command will show:
 [Errno 2] No such file or directory: '/Users/philippe/.minid/minid-config.cfg'
following the first attempt logging in.

way out was to  manually create an empty `minid-config.cfg` under `/.minid/` folder and running the `minid login` command

more details on my experience using this version of the client can be found here:
https://github.com/nih-cfde/the-fair-cookbook/blob/dev/docs/content/recipes/minids.md#Minid%20Client%20Configuration

**Comment by NickolausDS** [comment]
Thanks! I was able to reproduce, I'll have a fix shortly.
