### ISSUE TITLE
How to register non-local file

### ISSUE THREAD

**Issue by rpwagner** [ini-bdds/minid#58]
How can I provide the location, filename, and checksum via the CLI to register a new file that isn't on my local file system?

**Comment by NickolausDS** [comment]
Was that an original feature of the CLI? We could definitely add it, but I'm a little curious about the use-case. Previously, when I had a bunch of checksums for remote files I would do so in a python script rather than via the CLI. At that point my use-case was complex enough I wanted to script it. The CLI was more for trivial or one-off use cases where minting an identifier by hand  was doable. 

However is just how I have previously used the CLI. We may simply be able to add a flag to the register command to add this.

**Comment by rpwagner** [comment]
I don't know if it was an original feature. The use case is someone who generates a list of checksums from another system or maybe cloud storage, along with locations, then wants to use a Bash script and not work with the Python API. I'd suggest this for both registering a single file, and as a batch import where a list of files, checksums, and locations can be passed via CSV or TSV file.

**Comment by NickolausDS** [comment]
I'm seeing a couple different major features here. The current Minid CLI is pretty simple and not well suited for bash scripting at the moment. It doesn't cleanly respect stderr and stdout for output and doesn't map errors to exit codes. If we're interested in a rich CLI experience, we may also want to upgrade the CLI to use Click, so we can get other quality-of-life features like auto-complete and coloring. 

Batch registering sounds like a separate feature. The SDK already supports batch registering remote file manifests, and it would make sense for Minid to support that if we were to add CSVs and TSVs. `batch-register` could be a new minid CLI command.

**Comment by rpwagner** [comment]
If @mikedarcy concurs, the batch register feature would be my choice.

**Comment by mikedarcy** [comment]
Yes, the batch register mechanism was intended to cover this use case. The `1.3.0` version of the CLI had a `--batch-register` option that needs to be added back to the `2.0.0` CLI code. 

It is possible to use the [`create-rfm-from-file`](https://github.com/fair-research/bdbag/blob/master/doc/utils.md#create-rfm-from-file) function from `bdbag-utils` to create a RFM from CSV/TSV and then feed that directly into the `batch-register` function. This is in fact how I prepared bags for GTEX data in the DCPPC days. I would recommend using this workflow for the time being and not add any new code to support it, other than bringing the `--batch-register` CLI arg back.

There is an existing tutorial for how to do this workflow using the [`create-rfm-from-filesystem`](https://github.com/fair-research/fair-tutorials/blob/master/bag-minid/tutorial-1.md) logic. With a little effort we can add another tutorial that shows how to do the flow using `create-rfm-from-file`. I suspect it is probably a worthwhile task.

**Comment by NickolausDS** [comment]
`--batch-register` has already been implemented both in the SDK and the CLI at #44. There shouldn't be anything else to add if we can lean on bdbag-utils for creating rfms. Please reopen if anything else is missing.
