### ISSUE TITLE
EZID Landing Page is no longer applicable in minid 2.0

### ISSUE THREAD

**Issue by mikedarcy** [ini-bdds/minid#59]
This [code](https://github.com/fair-research/minid/blob/39606073a88e8ba85491e9ad371c403ed91ed764/minid/commands/cli.py#L123)  to pretty-print minid data should no longer include `EZID Landing Page` since Handle-based minids will not resolve at `https://ezid.cdlib.org/id/{id}`.

**Comment by NickolausDS** [comment]
Thanks good to note. 

Noting a similar issue: #57
