### ISSUE TITLE
Minid client and/or server conflates test and non-test namespaces

### ISSUE THREAD

**Issue by jonathancrabtree** [ini-bdds/minid#75]
I registered a number of minids using the latest (2.0.0b5) minid client and the "--test" flag. Some days later I attempted to register non-test minids for those same files (using the batch-register command and no "--test" flag.) However, instead of minting new non-test minids for the files, the client returned the previously-created test minids. I assume/hope this isn't the intended behavior. 

Here's a test case, assuming that the following test namespace minid has not yet been garbage collected:

> % cat test.json
> [
>   {
>     "length": 6321855247,
>     "filename": "SRS011061_hmrac2.tar.bz2",
>     "url": "",
>     "sha256": "35ecbea09d43ef1922701ee85b1a8841646ae68909a943f99877193472b2d0cc"
>   }
> ]
> % minid batch-register test.json
> [
>   {
>     "length": 6321855247,
>     "filename": "SRS011061_hmrac2.tar.bz2",
>     "url": "hdl:20.500.12633/1QNKMX8127Qa9",
>     "sha256": "35ecbea09d43ef1922701ee85b1a8841646ae68909a943f99877193472b2d0cc"
>   }
> ]
> % minid batch-register --no-test test.json
> [
>   {
>     "length": 6321855247,
>     "filename": "SRS011061_hmrac2.tar.bz2",
>     "url": "hdl:20.500.12633/1QNKMX8127Qa9",
>     "sha256": "35ecbea09d43ef1922701ee85b1a8841646ae68909a943f99877193472b2d0cc"
>   }
> ]

Note that hdl:20.500.12633 is the minid.test namespace and the client was asked to register the minid in the non-test namespace.

**Comment by NickolausDS** [comment]
I was able to recreate the behavior here. The batching behavior does a lookup using the given checksum to determine whether a Minid has already been minted, but doesn't appear to check which namespace the existing Minid resided in. This should also check that the namespace matches before returning a Minid to avoid this problem. 

@mikedarcy do you agree?

**Comment by mikedarcy** [comment]
Yes, this was likely an oversight when implementing the batch feature.

**Comment by NickolausDS** [comment]
Hey all, we decided to make some changes based on this issue. I think the new behavior will be a better fit, but I welcome your feedback. 

Pull Request: #77

**Comment by NickolausDS** [comment]
The PR above has been merged and we created a new Beta 6 release. The new batch-register functionality is a little different and should fix the problem you were having before. It now prefers creating new minids for everything by default. The new `--update-if-exists` flag will attempt to update an existing Minid if the checksums are the same. If the checksums are not the same, it will replace the existing Minid with a new one. If the namespaces differ, a new Minid will always be created. 

Feel free to reopen this issue or create a new one if you would like to continue the discussion. Thanks.
