### ISSUE TITLE
minid batch-register returns id based solely on SHA256 checksum

### ISSUE THREAD

**Issue by jonathancrabtree** [ini-bdds/minid#76]
I registered a batch of 5000 files using minid batch-register. Among those 5000 files were 2 files of zero length. Both were assigned the same minid, which turns out to be a minid associated with another zero-length file registered months ago (in the test namespace and by another user):

>   {
>     "length": 0,
>     "filename": "SRS018300.rapsearch2.m8",
>     "url": "hdl:20.500.12633/112XUQ6kleEms",
>     "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
>   }, 
>  {
>     "length": 0,
>     "filename": "SRS020340.rapsearch2.m8",
>     "url": "hdl:20.500.12633/112XUQ6kleEms",
>     "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
>   },

Here's what minid check says for this minid:

> % minid check "hdl:20.500.12633/112XUQ6kleEms"
>
> Minid:               minid.test:112XUQ6kleEms
> Title:               ../foo.txt
> Checksums:           e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 (sha256)
> Size:                0 bytes
> Created:             Thursday, April 16, 2020 17:54:05 EDT
> Updated:             Thursday, April 16, 2020 17:54:05 EDT
> Landing Page:        https://identifiers.fair-research.org/hdl:20.500.12633/112XUQ6kleEms
> Locations:           
> Active:              True
> Replaces:            
> Replaced By:

Leaving aside the (admittedly very very very) unlikely possibility of a SHA256 collision, it seems like the minid registration should at least take the Title into account when determining uniqueness. And when not using the batch-register command it does seem to do what I would expect (i.e., mint a new id even if the SHA256 checksum is the same as an existing minid):

> % touch my-file.txt
> % minid register --test my-file.txt
> Minid:               minid.test:IkhOBkZfd1rw
> Title:               my-file.txt
> Checksums:           e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 (sha256)
> Size:                0 bytes
> Created:             Tuesday, August 10, 2021 15:28:30 EDT
> Updated:             Tuesday, August 10, 2021 15:28:30 EDT
> Landing Page:        https://identifiers.fair-research.org/hdl:20.500.12633/IkhOBkZfd1rw
> Locations:           
> Active:              True
> Replaces:            
> Replaced By:
> 
> % minid check 'minid.test:IkhOBkZfd1rw'
> Minid:               minid.test:IkhOBkZfd1rw
> Title:               my-file.txt
> Checksums:           e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 (sha256)
> Size:                0 bytes
> Created:             Tuesday, August 10, 2021 15:28:30 EDT
> Updated:             Tuesday, August 10, 2021 15:28:30 EDT
> Landing Page:        https://identifiers.fair-research.org/hdl:20.500.12633/IkhOBkZfd1rw
> Locations:           
> Active:              True
> Replaces:            
> Replaced By:

It seems like this may be related to #75 although in this case the lookup/uniqueness check needs to take into account (at the very least) namespace, checksum, and title/filename.

**Comment by NickolausDS** [comment]
The new changes to batch register should fix this problem. Instead of the batch register functionality attempting to retrieve a minid based on checksum, it will instead compare the checksum on the existing minid in the URL field, and only re-use it if the content checksums match (and if the `--update-if-exists` is given).

See also #75 and #77
